package no.nb.nifi.tekst.util

object NiFiAttributes {
    const val UUID: String = "uuid"
    const val MIME_TYPE: String = "mime.type"
    const val HASH_VALUE: String = "hash.value"
    const val HASH_WHEN_READ: String = "hash.when.read"
    const val FILENAME: String = "filename"
    const val FILE_CREATIONTIME: String = "file.creationTime"
    const val FILE_URN: String = "file.urn"
    const val FILE_SIZE: String = "file.size"
    const val ORIGINAL_FILENAME: String = "original.filename"
    const val PATH: String = "path"
    const val ABSOLUTE_PATH: String = "absolute.path"
    const val FRAGMENT_IDENTIFIER: String = "fragment.identifier"
    const val FRAGMENT_INDEX: String = "fragment.index"
    const val FRAGMENT_COUNT: String = "fragment.count"
    const val SEGMENT_ORIGINAL_FILENAME: String = "segment.original.filename"
    const val URN: String = "urn"
    const val ERROR_MESSAGE: String = "error.message"
    const val ERROR_LEVEL: String = "error.level"
    const val IDENTIFIERS: String = "identifiers"
    const val COMPONENT_IDENTIFIER: String = "component.identifier"
    const val COMPONENT_INDEX: String = "component.index"
    const val COMPONENT_TYPE: String = "component.type"
    const val COMPONENT_COUNT: String = "component.count"
    const val COMPONENT_PRESENT: String = "component.present.*"
    const val PLM_ID: String = "plm.id"
    const val PLM_SKIPPED_UPDATE: String = "plm.skipped.update"
    const val PROD_DB_ID: String = "prod.db.id"
    const val PROD_DB_STEP_ID: String = "prod.db.step.id"
    const val TWO_SIDED: String = "twoSided"
    const val BARCODE: String = "barcode"
    const val FOLDER_NAME: String = "foldername"
    const val PRODUCTION_LINE_TAG: String = "productionline.tag"
    const val SCANNER_MANUFACTURER: String = "scanner.manufacturer"
    const val SCANNER_MODEL: String = "scanner.model"
    const val SCANNER_SOFTWARE: String = "scanner.software"
    const val WAIT_START_TIMESTAMP: String = "nb.wait.start.timestamp"
    const val HTTP_RESPONSE: String = "http.response"
}